"""
SaviorAI Demo Email Service

Sends Level 3 emergency alerts via email during demo mode.
Uses Gmail SMTP with app password from .env.
"""

import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
import os


def send_demo_counsellor_email(
    student_name: str,
    risk_score: float,
    reasoning: str,
    intervention_message: str,
    consecutive_low_days: int
) -> bool:
    """
    Sends Level 3 emergency alert email during demo mode.
    
    Args:
        student_name: Student's full name
        risk_score: Risk score (0-100)
        reasoning: Agent's decision reasoning
        intervention_message: GPT-generated message for student
        consecutive_low_days: Number of consecutive low mood days
    
    Returns:
        True if email sent successfully, False otherwise
    """
    smtp_host = os.getenv("SMTP_HOST", "smtp.gmail.com")
    smtp_port = int(os.getenv("SMTP_PORT", "587"))
    smtp_user = os.getenv("SMTP_USER")
    smtp_password = os.getenv("SMTP_PASSWORD")
    to_email = os.getenv("DEMO_COUNSELLOR_EMAIL")
    
    if not all([smtp_user, smtp_password, to_email]):
        print("⚠️  SMTP not configured. Skipping email. Check .env file.")
        print(f"   SMTP_USER: {'✓' if smtp_user else '✗'}")
        print(f"   SMTP_PASSWORD: {'✓' if smtp_password else '✗'}")
        print(f"   DEMO_COUNSELLOR_EMAIL: {'✓' if to_email else '✗'}")
        return False
    
    subject = f"🚨 URGENT: {student_name} — Emergency Mental Health Alert"
    
    html_body = f"""
<div style="font-family: Arial, sans-serif; max-width: 600px; border: 2px solid #e74c3c; border-radius: 8px; padding: 20px; margin: 20px auto;">
    <h2 style="color: #e74c3c; margin-top: 0;">🚨 Emergency Alert — SaviorAI</h2>
    
    <div style="background: #fff3cd; border-left: 4px solid #ffc107; padding: 12px; margin: 16px 0;">
        <strong style="color: #856404;">⚡ Immediate Action Required</strong>
        <p style="margin: 8px 0 0 0; color: #856404;">Please contact this student within the next 2 hours.</p>
    </div>
    
    <table style="width: 100%; border-collapse: collapse; margin: 16px 0;">
        <tr style="border-bottom: 1px solid #eee;">
            <td style="padding: 8px; font-weight: bold;">Student:</td>
            <td style="padding: 8px;">{student_name}</td>
        </tr>
        <tr style="border-bottom: 1px solid #eee;">
            <td style="padding: 8px; font-weight: bold;">Risk Score:</td>
            <td style="padding: 8px;"><span style="color: #e74c3c; font-size: 18px; font-weight: bold;">{risk_score:.0f}/100</span></td>
        </tr>
        <tr style="border-bottom: 1px solid #eee;">
            <td style="padding: 8px; font-weight: bold;">Intervention Level:</td>
            <td style="padding: 8px;"><strong>Level 3</strong> — Emergency Escalation</td>
        </tr>
        <tr>
            <td style="padding: 8px; font-weight: bold;">Consecutive Low Days:</td>
            <td style="padding: 8px;">{consecutive_low_days}</td>
        </tr>
    </table>
    
    <hr style="border: none; border-top: 1px solid #eee; margin: 20px 0;"/>
    
    <h3 style="color: #333; font-size: 16px;">🤖 Agent Reasoning:</h3>
    <div style="background: #f8f9fa; padding: 12px; border-radius: 4px; color: #555; line-height: 1.6;">
        {reasoning.replace(chr(10), '<br/>')}
    </div>
    
    <hr style="border: none; border-top: 1px solid #eee; margin: 20px 0;"/>
    
    <h3 style="color: #333; font-size: 16px;">💬 Recommended Message to Student:</h3>
    <div style="background: #e8f4f8; padding: 12px; border-radius: 4px; font-style: italic; color: #333; line-height: 1.6; border-left: 4px solid #17a2b8;">
        {intervention_message.replace(chr(10), '<br/>')}
    </div>
    
    <hr style="border: none; border-top: 1px solid #eee; margin: 20px 0;"/>
    
    <div style="background: #f8d7da; border-left: 4px solid #e74c3c; padding: 12px; margin: 16px 0;">
        <p style="color: #721c24; margin: 0; font-weight: bold;">
            ⚡ This alert was generated autonomously by SaviorAI's multi-agent system.
        </p>
        <p style="color: #721c24; margin: 8px 0 0 0;">
            The system detected a high-confidence crisis pattern requiring immediate human intervention.
        </p>
    </div>
    
    <hr style="border: none; border-top: 1px solid #eee; margin: 20px 0;"/>
    
    <p style="color: #999; font-size: 12px; text-align: center; margin: 16px 0 0 0;">
        Generated by SaviorAI Autonomous Mental Health Monitoring System<br/>
        <a href="https://github.com/yourusername/SaviorAI" style="color: #17a2b8;">GitHub Repository</a>
    </p>
</div>
"""
    
    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = smtp_user
    msg["To"] = to_email
    msg.attach(MIMEText(html_body, "html"))
    
    try:
        with smtplib.SMTP(smtp_host, smtp_port) as server:
            server.starttls()
            server.login(smtp_user, smtp_password)
            server.sendmail(smtp_user, to_email, msg.as_string())
        
        print(f"✅ Emergency email sent to {to_email}")
        return True
        
    except Exception as e:
        print(f"❌ Email failed: {e}")
        return False
